### ISSUE TITLE
Java 12 support?

### ISSUE THREAD

**Issue by matmadz** [Ivorforce/IvToolkit#15]
Is there any chance of this mod supporting Java 12? When I try to launch it with a newer JDK than 8, I get the following error:

```
[0412/180843:INFO:GameCallbacks.cpp(198)] game/game () info [18:08:43] [main/ERROR] [LaunchWrapper]: Unable to launch

[0412/180843:INFO:GameCallbacks.cpp(198)] game/game () info java.lang.NullPointerException: null

[0412/180843:INFO:GameCallbacks.cpp(198)] game/game () info at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast(SystemUtils.java:1626) ~[commons-lang3-3.5.jar:3.5]

[0412/180843:INFO:GameCallbacks.cpp(198)] game/game () info at ivorius.ivtoolkit.tools.JavaCompatibility.requireJava8(JavaCompatibility.java:40) ~[JavaCompatibility.class:?]

[0412/180843:INFO:GameCallbacks.cpp(198)] game/game () info at ivorius.ivtoolkit.IvToolkitLoadingPlugin.getASMTransformerClass(IvToolkitLoadingPlugin.java:38) ~[IvToolkit-1.3.3-1.12.jar:?]

[0412/180843:INFO:GameCallbacks.cpp(198)] game/game () info at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:129) ~[forge-1.12.2-14.23.5.2796.jar:?]

[0412/180843:INFO:GameCallbacks.cpp(198)] game/game () info at net.minecraft.launchwrapper.Launch.launch(Launch.java:137) [launchwrapper-2.0.jar:?]

[0412/180843:INFO:GameCallbacks.cpp(198)] game/game () info at net.minecraft.launchwrapper.Launch.main(Launch.java:23) [launchwrapper-2.0.jar:?]

[0412/180843:INFO:GameCallbacks.cpp(198)] game/game () info Exception in thread "main" net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException

[0412/180843:INFO:GameCallbacks.cpp(198)] game/game () info at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)

[0412/180843:INFO:GameCallbacks.cpp(198)] game/game () info at java.base/java.lang.SecurityManager.checkExit(SecurityManager.java:620)

[0412/180843:INFO:GameCallbacks.cpp(198)] game/game () info at java.base/java.lang.Runtime.exit(Runtime.java:111)

[0412/180843:INFO:GameCallbacks.cpp(198)] game/game () info at java.base/java.lang.System.exit(System.java:345)

[0412/180843:INFO:GameCallbacks.cpp(198)] game/game () info at net.minecraft.launchwrapper.Launch.launch(Launch.java:160)

[0412/180843:INFO:GameCallbacks.cpp(198)] game/game () info at net.minecraft.launchwrapper.Launch.main(Launch.java:23)

[0412/180844:INFO:GameCallbacks.cpp(198)] launcher/monitor (Process Monitor) fatal Process crashed with exit code 1

```

**Comment by ROMVoid95** [comment]
a little late, but out of curiosity why use any other jdk than the version mojang is still on? Forge can't even use antyhing above 1.8 (tweaks can be made to make J10 work but breaks things elsewhere)
