### ISSUE TITLE
game couldnt load new world

### ISSUE THREAD

**Issue by pianted** [Ivorforce/IvToolkit#16]
mustve been IvToolkit (used for recurrent complex) that caused it

this is the crash report:

> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  OTGCorePlugin (OTG-Core.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  Quark Plugin (Quark-r1.5-154.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 7/2/19 6:59 PM
Description: Ticking entity

java.lang.NoClassDefFoundError: com/pg85/otg/forge/dimensions/WorldProviderOTG
	at com.pg85.otg.forge.asm.OTGHooks.getGravityFactor(OTGHooks.java:26)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1977)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at com.animania.common.entities.amphibians.EntityAmphibian.func_70636_d(EntityAmphibian.java:263)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.pg85.otg.forge.dimensions.WorldProviderOTG
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.pg85.otg.forge.asm.OTGHooks.getGravityFactor(OTGHooks.java:26)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1977)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at com.animania.common.entities.amphibians.EntityAmphibian.func_70636_d(EntityAmphibian.java:263)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: animania:toad (com.animania.common.entities.amphibians.EntityToad)
	Entity ID: 15
	Entity Name: Toad
	Entity's Exact location: -320.50, 70.00, 112.50
	Entity's Block location: World: (-321,70,112), Chunk: (at 15,4,0 in -21,7; contains blocks -336,0,112 to -321,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World--
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 6180020068691085130
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-172,64,280), Chunk: (at 4,4,8 in -11,17; contains blocks -176,0,272 to -161,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2 game time, 2 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 52362 (now: false), thunder time: 73370 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 595783816 bytes (568 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                             | Signature                                |
	|:------ |:-------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ivtoolkit            | 1.3.3-1.12        | minecraft.jar                                      | None                                     |
	| LCHIJA | otgcore              | 1.12.2 - v7       | minecraft.jar                                      | None                                     |
	| LCHIJA | craftstudioapi       | 1.0.0             | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHIJA | animania             | 1.6.2             | animania-1.12.2-1.6.2.jar                          | None                                     |
	| LCHIJA | jei                  | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                          | None                                     |
	| LCHIJA | quark                | r1.5-154          | Quark-r1.5-154.jar                                 | None                                     |
	| LCHIJA | autoreglib           | 1.3-30            | AutoRegLib-1.3-30.jar                              | None                                     |
	| LCHIJA | chameleon            | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
	| LCHIJA | chisel               | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
	| LCHIJA | dynamictrees         | 1.12.2-0.9.5      | DynamicTrees-1.12.2-0.9.5.jar                      | None                                     |
	| LCHIJA | gardenstuff          | 1.12-2.1.1        | GardenStuff-1.12-2.1.1.jar                         | None                                     |
	| LCHIJA | waila                | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHIJA | recipehandler        | 0.13              | NoMoreRecipeConflict-0.13(1.12.2).jar              | None                                     |
	| LCHIJA | oreexcavation        | 1.4.140           | OreExcavation-1.4.140.jar                          | None                                     |
	| LCHIJA | placebo              | 1.5.1             | Placebo-1.12.2-1.5.1.jar                           | None                                     |
	| LCHIJA | plants2              | 2.10.7            | Plants-1.12.2-2.10.7.jar                           | None                                     |
	| LCHIJA | quarkoddities        | 1                 | QuarkOddities-1.12.2.jar                           | None                                     |
	| LCHIJA | reccomplex           | 1.4.8.1           | RecurrentComplex-1.4.8.1.jar                       | None                                     |
	| LCHIJA | rustic               | 1.1.0             | rustic-1.1.0.jar                                   | None                                     |
	| LCHIJA | unlimitedchiselworks | 0.2.2             | UnlimitedChiselWorks-0.2.2.jar                     | None                                     |

	Loaded coremods (and transformers): 
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
Quark Plugin (Quark-r1.5-154.jar)
  vazkii.quark.base.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.17 High.zip
	OpenGlVersion: 4.5.13474 Compatibility Profile Context 22.19.162.4
	OpenGlRenderer: AMD Radeon R9 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by arcticKitKat** [comment]
Yeah... Is there a fixed version for Ivtoolkit that I could use, anyone?
